### ISSUE TITLE
Update for 1.20.4 (Fabric)?

### ISSUE THREAD

**Issue by seriousfreezing** [MerpisMe/Jump_Sounds#2]

**Comment by MerpisMe** [comment]
it's already compatible with 1.20.4, you just have to modify the fabric.mod.json file

**Comment by seriousfreezing** [comment]
In any case, would it still be supported even if you modified the mod file itself?

**Comment by MerpisMe** [comment]
> In any case, would it still be supported even if you modified the mod file itself?

yep
